import type { ControlManifest, SystemManifest, AiCouncilRequest, EvidenceRecord, RiskFinding } from "../types";

// ── WESCO Demo Seed Data ──────────────────────────────────────────────
// Seeded from the PRD for a realistic WESCO demo experience.

export function demoWescoSystems(): SystemManifest[] {
  const now = new Date().toISOString();
  return [
    {
      id: "sys-oracle",
      name: "Oracle EBS",
      category: "erp",
      ownerPersonId: "wescop1",
      soxInScope: true,
      dataSensitivity: "regulated",
      integrationStatus: "connected",
      connectedHumanIds: ["wescop1", "wescop2"],
      connectedAgentIds: [],
      connectedControlIds: ["ctrl-payables", "ctrl-procurement"],
      riskFindings: [],
      approvalRequirements: [
        { gate: "SOX_SYSTEM_ACCESS", met: true, approver: "julie.chen@wesco.com" },
        { gate: "FINANCIAL_SYSTEM", met: true, approver: "marcus.webb@wesco.com" },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sys-workday",
      name: "Workday",
      category: "hris",
      ownerPersonId: "wescop3",
      soxInScope: true,
      dataSensitivity: "confidential",
      integrationStatus: "connected",
      connectedHumanIds: ["wescop3", "wescop4"],
      connectedAgentIds: [],
      connectedControlIds: ["ctrl-identity"],
      riskFindings: [],
      approvalRequirements: [
        { gate: "HR_SYSTEM_ACCESS", met: true, approver: "lisa.park@wesco.com" },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sys-salesforce",
      name: "Salesforce",
      category: "crm",
      ownerPersonId: "wescop5",
      soxInScope: false,
      dataSensitivity: "internal",
      integrationStatus: "connected",
      connectedHumanIds: ["wescop5", "wescop6", "wescop1"],
      connectedAgentIds: [],
      connectedControlIds: [],
      riskFindings: [],
      approvalRequirements: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sys-servicenow",
      name: "ServiceNow",
      category: "other",
      ownerPersonId: "wescop4",
      soxInScope: false,
      dataSensitivity: "internal",
      integrationStatus: "connected",
      connectedHumanIds: ["wescop4", "wescop6"],
      connectedAgentIds: [],
      connectedControlIds: [],
      riskFindings: [],
      approvalRequirements: [],
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function demoWescoControls(): ControlManifest[] {
  const now = new Date().toISOString();
  return [
    {
      id: "ctrl-payables",
      controlId: "WESCO-SOX-101",
      name: "Vendor Payment Processing Controls",
      description: "Ensures all vendor payments over $10k have dual authorization and matching PO. Covers Oracle EBS payables module.",
      ownerPersonId: "wescop1",
      process: "Accounts Payable",
      relatedRisk: "Unauthorized vendor payments and financial misstatement",
      frequency: "monthly",
      systemIds: ["sys-oracle"],
      evidenceRequired: ["Approved PO report", "Payment authorization log", "Exception report"],
      soxRelevant: true,
      relatedTaskIds: [],
      relatedAgentIds: [],
      approvalRequirements: [
        { gate: "SOX_OWNER_APPROVAL", met: true, approver: "julie.chen@wesco.com" },
      ],
      status: "active",
      source: "policy_document",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ctrl-procurement",
      controlId: "WESCO-SOX-102",
      name: "Procurement to Pay (P2P) Controls",
      description: "Covers purchase order creation, goods receipt matching, and invoice verification in Oracle EBS.",
      ownerPersonId: "wescop1",
      process: "Procurement",
      relatedRisk: "Procurement fraud and vendor master manipulation",
      frequency: "monthly",
      systemIds: ["sys-oracle"],
      evidenceRequired: ["PO change log", "Goods receipt discrepancy report", "Invoice hold report"],
      soxRelevant: true,
      relatedTaskIds: [],
      relatedAgentIds: [],
      approvalRequirements: [
        { gate: "SOX_OWNER_APPROVAL", met: true, approver: "julie.chen@wesco.com" },
      ],
      status: "active",
      source: "policy_document",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ctrl-identity",
      controlId: "WESCO-SOX-201",
      name: "Identity and Access Management Controls",
      description: "Covers user provisioning, deprovisioning, and access reviews across SOX in-scope systems.",
      ownerPersonId: "wescop3",
      process: "Identity Governance",
      relatedRisk: "Unauthorized system access and SOD violations",
      frequency: "quarterly",
      systemIds: ["sys-workday", "sys-oracle"],
      evidenceRequired: ["Access review sign-off", "User provisioning log", "SOD violation report"],
      soxRelevant: true,
      relatedTaskIds: [],
      relatedAgentIds: [],
      approvalRequirements: [
        { gate: "SOX_OWNER_APPROVAL", met: true, approver: "lisa.park@wesco.com" },
      ],
      status: "active",
      source: "policy_document",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ctrl-forecast",
      controlId: "WESCO-SOX-301",
      name: "Financial Forecasting Controls",
      description: "Governs the quarterly forecast process including revenue projections, expense accruals, and variance analysis.",
      ownerPersonId: "wescop2",
      process: "Financial Planning",
      relatedRisk: "Material misstatement in financial forecasts",
      frequency: "quarterly",
      systemIds: [],
      evidenceRequired: ["Forecast approval record", "Variance analysis documentation"],
      soxRelevant: false,
      relatedTaskIds: [],
      relatedAgentIds: [],
      approvalRequirements: [
        { gate: "FORECAST_APPROVAL", met: true, approver: "marcus.webb@wesco.com" },
      ],
      status: "active",
      source: "manual",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function demoWescoEvidenceRecords(): EvidenceRecord[] {
  const now = new Date().toISOString();
  return [
    {
      id: "evt-council-001",
      type: "approval",
      subjectType: "request",
      subjectId: "aic-req-001",
      actor: "julie.chen@wesco.com",
      timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
      summary: "AI Council approved the Financial Summary Agent request. Oracle EBS access granted with read-only scope.",
      source: {
        kind: "manual_action",
        quote: "Approved after review of business case and system access requirements.",
      },
    },
    {
      id: "evt-cert-001",
      type: "birth_certificate",
      subjectType: "agent",
      subjectId: "agent-fin-summary-001",
      actor: "system",
      timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
      summary: "Agent Birth Certificate created for Financial Summary Agent (v1).",
    },
    {
      id: "evt-transfer-001",
      type: "transfer",
      subjectType: "agent",
      subjectId: "agent-vendor-scan-001",
      actor: "lisa.park@wesco.com",
      timestamp: new Date(Date.now() - 86400000 * 1).toISOString(),
      summary: "Vendor Risk Scan agent reassigned to Marcus Webb. Authority comparison completed; 2 system mismatches flagged.",
    },
  ];
}

export function demoWescoRiskFindings(): RiskFinding[] {
  const now = new Date().toISOString();
  return [
    {
      id: "risk-orphan-001",
      severity: "high",
      category: "orphaned_agent",
      title: "Orphaned Agent: Vendor Risk Scan",
      plainEnglishDescription: "Agent 'Vendor Risk Scan' was owned by Dana Fischer, who has been offboarded. The agent has no active accountable owner.",
      whyItMatters: "Orphaned agents can drift beyond their approved scope or continue operating against outdated policies.",
      recommendedAction: "Reassign to a new owner or suspend the agent. An AI Council review may be required.",
      relatedAgentIds: ["agent-vendor-scan-001"],
      relatedPersonIds: ["wescop6"],
      relatedSystemIds: ["sys-oracle"],
      relatedControlIds: ["ctrl-payables"],
      status: "open",
      evidenceIds: ["evt-transfer-001"],
      createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    },
    {
      id: "risk-sox-system-001",
      severity: "medium",
      category: "sox_system_access",
      title: "Unreviewed Agent Access to Oracle EBS",
      plainEnglishDescription: "Financial Summary Agent has read access to Oracle EBS, a SOX-in-scope system, but the access was not reviewed by a controls owner.",
      whyItMatters: "SOX controls require that all system access by automated agents is reviewed and approved by the control owner.",
      recommendedAction: "Submit a SOX access review request for this agent. The Oracle EBS control owner must approve.",
      relatedAgentIds: ["agent-fin-summary-001"],
      relatedPersonIds: ["wescop1", "wescop2"],
      relatedSystemIds: ["sys-oracle"],
      relatedControlIds: ["ctrl-payables"],
      status: "open",
      evidenceIds: ["evt-cert-001"],
      createdAt: now,
    },
    {
      id: "risk-drift-001",
      severity: "low",
      category: "drift",
      title: "Minor Scope Drift: PO Monitor Agent",
      plainEnglishDescription: "Agent 'PO Monitor' was approved for read-only Oracle access but a draft permission was detected in the latest export.",
      whyItMatters: "Scope drift can accumulate and lead to unauthorized system modifications.",
      recommendedAction: "Review the agent's current manifest and recompile. If draft access is needed, submit an AI Council scope change request.",
      relatedAgentIds: ["agent-po-monitor-001"],
      relatedPersonIds: ["wescop1"],
      relatedSystemIds: ["sys-oracle"],
      relatedControlIds: ["ctrl-procurement"],
      status: "open",
      evidenceIds: [],
      createdAt: now,
    },
  ];
}

export function demoWescoAiCouncilRequests(): AiCouncilRequest[] {
  const now = new Date().toISOString();
  return [
    {
      id: "aic-req-002",
      requesterId: "wescop2",
      department: "Finance",
      businessProblem: "Our monthly account reconciliation process takes 3 days manually. We need an agent to automate matching between Oracle EBS and bank statements.",
      proposedTask: "Reconcile monthly bank statements against Oracle EBS general ledger entries and flag discrepancies.",
      expectedBenefit: "Reduce monthly close from 3 days to 4 hours and eliminate manual matching errors.",
      systemsTouched: ["sys-oracle"],
      dataSensitivity: "regulated",
      soxRelevant: true,
      humanOwnerId: "wescop2",
      riskTier: "high",
      approvalRequirements: [
        { gate: "SOX_IMPACT_REVIEW", met: false },
        { gate: "FINANCIAL_SYSTEM_ACCESS", met: false },
        { gate: "AI_COUNCIL_APPROVAL", met: false },
      ],
      status: "under_review",
      priority: "high",
      reviewerIds: ["wescop1", "wescop3"],
      evidenceIds: [],
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      updatedAt: now,
    },
    {
      id: "aic-req-003",
      requesterId: "wescop5",
      department: "Sales",
      businessProblem: "Sales team spends 5 hours per week manually updating Salesforce deal stages and pipeline notes.",
      proposedTask: "Update Salesforce deal stages and pipeline notes based on Slack activity and email summaries.",
      expectedBenefit: "Recover 5 hours/week per sales rep and improve pipeline accuracy.",
      systemsTouched: ["sys-salesforce"],
      dataSensitivity: "internal",
      soxRelevant: false,
      humanOwnerId: "wescop5",
      riskTier: "medium",
      approvalRequirements: [
        { gate: "CRM_SYSTEM_ACCESS", met: false },
        { gate: "AI_COUNCIL_APPROVAL", met: false },
      ],
      status: "submitted",
      priority: "medium",
      reviewerIds: ["wescop4"],
      evidenceIds: [],
      createdAt: now,
      updatedAt: now,
    },
  ];
}
