import type { WorkflowTemplate } from "@/types";

function template(base: Omit<WorkflowTemplate, "scope">): WorkflowTemplate {
  return { ...base, scope: "global" };
}

export const GLOBAL_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  template({
    id: "wf-weekly-status-summary",
    name: "Weekly status summary",
    category: "summary",
    description: "Summarize current work, risks, blockers, and approvals into a recurring internal brief.",
    delegationFit: "high",
    requiredInputs: [
      { name: "source records", description: "Work items, accounts, claims, tickets, or project updates to summarize.", required: true },
      { name: "date range", description: "The reporting window.", required: true, example: "previous business week" },
      { name: "recipient", description: "The human reviewer or team receiving the brief.", required: true },
    ],
    requiredTools: [
      { type: "mcp", name: "source system", permission: "read", required: true },
      { type: "email", name: "internal draft", permission: "draft", required: false },
    ],
    steps: [
      { order: 1, instruction: "Read the source records for the reporting window." },
      { order: 2, instruction: "Group records by status, owner, amount, and risk." },
      { order: 3, instruction: "Draft a brief with exceptions, missing data, and approval needs." },
    ],
    outputSchema: { format: "brief", requiredSections: ["summary", "exceptions", "approvals needed", "next actions"] },
    definitionOfDone: ["Includes count and aging", "Flags missing data", "Names owner and next action", "Never sends externally without approval"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["sending or publishing the brief"], blockedActions: ["changing source records", "approving exceptions"] },
    riskChecks: ["missing source fields", "stale records", "external recipient"],
    evalTests: [{ name: "sample summary", inputExample: "10 open records with 2 missing owners", expectedOutput: "Brief flags missing owners and separates exceptions." }],
    missingInfoQuestions: ["Which source system should the agent read?", "Who receives the brief?", "What cadence should it use?"],
  }),
  template({
    id: "wf-claims-summary",
    name: "Claims summary brief",
    category: "summary",
    description: "Summarize open customer or revenue claims with financial exposure, aging, owner, and approval needs.",
    delegationFit: "high",
    requiredInputs: [
      { name: "claims source", description: "System containing claims records.", required: true, example: "Salesforce claims object" },
      { name: "claim fields", description: "Status, amount, owner, aging, SLA, blockers.", required: true },
    ],
    requiredTools: [{ type: "mcp", name: "Salesforce", permission: "read", required: true }],
    steps: [
      { order: 1, instruction: "Pull open claims for the requested period." },
      { order: 2, instruction: "Group by status, owner, amount, and aging bucket." },
      { order: 3, instruction: "Draft an exceptions-first claims brief for human review." },
    ],
    outputSchema: { format: "brief", requiredSections: ["claim count", "dollar exposure", "aging", "exceptions", "approvals needed"] },
    definitionOfDone: ["Counts all open claims", "Shows dollar exposure", "Flags claims older than threshold", "Identifies missing data"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["claim approval", "customer communication"], blockedActions: ["approving claims", "editing customer records"] },
    riskChecks: ["PII exposure", "financial approval", "missing claim owner"],
    evalTests: [{ name: "missing owner test", inputExample: "10 claims, 1 missing owner", expectedOutput: "Brief includes all 10 and flags the missing owner." }],
    missingInfoQuestions: ["Where do claims live?", "What fields are required?", "What aging threshold matters?"],
  }),
  template({
    id: "wf-support-ticket-triage",
    name: "Support ticket triage",
    category: "routing",
    description: "Classify incoming support tickets, flag risk, and draft routing recommendations.",
    delegationFit: "high",
    requiredInputs: [{ name: "ticket queue", description: "Ticket list with requester, issue, severity, and owner.", required: true }],
    requiredTools: [{ type: "mcp", name: "Zendesk", permission: "read", required: true }],
    steps: [{ order: 1, instruction: "Read new tickets." }, { order: 2, instruction: "Classify severity and category." }, { order: 3, instruction: "Draft routing recommendation." }],
    outputSchema: { format: "table", requiredSections: ["ticket", "category", "severity", "suggested owner", "reason"] },
    definitionOfDone: ["Every ticket has a category", "High-risk items are flagged", "Recommendations cite evidence"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["closing tickets", "customer-facing replies"], blockedActions: ["closing tickets without approval"] },
    riskChecks: ["customer escalation", "security issue", "missing owner"],
    evalTests: [{ name: "severity routing", inputExample: "Three tickets with one outage report", expectedOutput: "Outage ticket marked high severity." }],
    missingInfoQuestions: ["Which queue should be triaged?", "Who approves routing changes?"],
  }),
  template({
    id: "wf-approval-packet",
    name: "Approval packet preparation",
    category: "approval_prep",
    description: "Prepare an internal packet with facts, evidence, risks, and recommended approval questions.",
    delegationFit: "medium",
    requiredInputs: [{ name: "request details", description: "The request needing approval and supporting facts.", required: true }],
    requiredTools: [{ type: "document_store", name: "policy documents", permission: "read", required: false }],
    steps: [{ order: 1, instruction: "Collect request facts." }, { order: 2, instruction: "Compare against approval policy." }, { order: 3, instruction: "Draft approval packet." }],
    outputSchema: { format: "brief", requiredSections: ["request", "policy context", "risks", "approval questions"] },
    definitionOfDone: ["Cites source facts", "Separates recommendation from decision", "Names human approver"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["final approval"], blockedActions: ["approving on behalf of the human"] },
    riskChecks: ["financial authority", "policy exception"],
    evalTests: [{ name: "approval boundary", inputExample: "Refund request above threshold", expectedOutput: "Packet says human approval required." }],
    missingInfoQuestions: ["Who approves this?", "Which policy applies?"],
  }),
  template({
    id: "wf-internal-update-draft",
    name: "Internal update draft",
    category: "drafting",
    description: "Draft an internal status update from source notes and known operating facts.",
    delegationFit: "high",
    requiredInputs: [{ name: "source notes", description: "Meeting notes, task records, or transcript excerpts.", required: true }],
    requiredTools: [{ type: "email", name: "email or Slack", permission: "draft", required: false }],
    steps: [{ order: 1, instruction: "Extract facts and open decisions." }, { order: 2, instruction: "Draft concise internal update." }],
    outputSchema: { format: "email_draft", requiredSections: ["context", "updates", "asks", "owner"] },
    definitionOfDone: ["Draft is internal", "Asks are explicit", "No unsupported commitments"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["sending"], blockedActions: ["external communication"] },
    riskChecks: ["unsupported promise", "external recipient"],
    evalTests: [{ name: "draft only", inputExample: "Meeting notes with two asks", expectedOutput: "Draft update includes both asks and stays unsent." }],
    missingInfoQuestions: ["Who receives the update?", "What tone/cadence should it use?"],
  }),
  template({
    id: "wf-pipeline-hygiene-review",
    name: "Pipeline hygiene review",
    category: "reporting",
    description: "Audit CRM pipeline records for missing fields, stale stages, and unowned deals, and draft a cleanup report.",
    delegationFit: "high",
    requiredInputs: [
      { name: "pipeline source", description: "CRM pipeline or deal list with stage, owner, amount, and last activity.", required: true, example: "HubSpot deals board" },
      { name: "hygiene rules", description: "Which fields are required and what counts as stale.", required: true, example: "no activity in 14 days" },
    ],
    requiredTools: [{ type: "mcp", name: "CRM", permission: "read", required: true }],
    steps: [
      { order: 1, instruction: "Read all open pipeline records." },
      { order: 2, instruction: "Check each record against the hygiene rules." },
      { order: 3, instruction: "Draft a report grouped by owner with the specific fix per record." },
    ],
    outputSchema: { format: "table", requiredSections: ["record", "owner", "issue", "suggested fix"] },
    definitionOfDone: ["Covers every open record", "Each issue names the rule it violates", "No record is edited"],
    approvalPolicy: { defaultMode: "read_only", approvalRequiredFor: ["any CRM edit"], blockedActions: ["editing or deleting CRM records"] },
    riskChecks: ["wrong-owner attribution", "stale rule definitions"],
    evalTests: [{ name: "stale detection", inputExample: "Five deals, two idle for 20 days", expectedOutput: "Report flags exactly the two idle deals." }],
    missingInfoQuestions: ["Which CRM and pipeline?", "What makes a record stale here?"],
  }),
  template({
    id: "wf-stale-deal-monitor",
    name: "Stale deal monitor",
    category: "monitoring",
    description: "Watch open deals for inactivity past a threshold and draft owner-by-owner nudges.",
    delegationFit: "high",
    requiredInputs: [
      { name: "deal source", description: "Open deals with stage, owner, and last-activity date.", required: true },
      { name: "staleness threshold", description: "Days of inactivity before a deal is flagged.", required: true, example: "14 days" },
    ],
    requiredTools: [
      { type: "mcp", name: "CRM", permission: "read", required: true },
      { type: "email", name: "owner nudge", permission: "draft", required: false },
    ],
    steps: [
      { order: 1, instruction: "Scan open deals on the agreed cadence." },
      { order: 2, instruction: "Flag deals past the inactivity threshold." },
      { order: 3, instruction: "Draft a short nudge per owner listing their stale deals." },
    ],
    outputSchema: { format: "brief", requiredSections: ["stale count", "by owner", "aging", "suggested next touch"] },
    definitionOfDone: ["Uses the agreed threshold", "Every flagged deal shows days idle", "Nudges stay drafts"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["sending nudges"], blockedActions: ["changing deal stages", "reassigning owners"] },
    riskChecks: ["false staleness from sync lag", "owner churn"],
    evalTests: [{ name: "threshold respected", inputExample: "Deal idle 13 days with 14-day threshold", expectedOutput: "Deal is not flagged." }],
    missingInfoQuestions: ["What inactivity threshold applies?", "Who receives the nudge drafts?"],
  }),
  template({
    id: "wf-onboarding-status-brief",
    name: "Customer onboarding status brief",
    category: "summary",
    description: "Summarize in-flight customer onboardings: stage, days-to-kickoff, blockers, and at-risk accounts.",
    delegationFit: "high",
    requiredInputs: [
      { name: "onboarding tracker", description: "Source listing accounts, stage, start date, owner, and blockers.", required: true },
      { name: "target runway", description: "Expected days from close to kickoff.", required: true, example: "21 days" },
    ],
    requiredTools: [{ type: "mcp", name: "onboarding tracker", permission: "read", required: true }],
    steps: [
      { order: 1, instruction: "Read all in-flight onboardings." },
      { order: 2, instruction: "Compare elapsed time against the target runway." },
      { order: 3, instruction: "Draft a brief leading with at-risk accounts and their blockers." },
    ],
    outputSchema: { format: "brief", requiredSections: ["in-flight count", "at-risk accounts", "blockers", "next actions"] },
    definitionOfDone: ["Every in-flight account appears", "At-risk accounts cite days elapsed", "Blockers name an owner"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["customer communication"], blockedActions: ["contacting customers", "changing kickoff dates"] },
    riskChecks: ["customer-visible delay", "missing tracker data"],
    evalTests: [{ name: "at-risk ordering", inputExample: "Three onboardings, one past runway", expectedOutput: "Overdue account leads the brief." }],
    missingInfoQuestions: ["Where is onboarding tracked?", "What runway counts as at-risk?"],
  }),
  template({
    id: "wf-invoice-reconciliation",
    name: "Invoice reconciliation",
    category: "reconciliation",
    description: "Compare invoices against orders or contracts, flag mismatches, and draft an exceptions report.",
    delegationFit: "medium",
    requiredInputs: [
      { name: "invoice source", description: "Invoices with amount, vendor/customer, and reference.", required: true },
      { name: "reference records", description: "Orders, contracts, or POs to reconcile against.", required: true },
    ],
    requiredTools: [
      { type: "mcp", name: "finance system", permission: "read", required: true },
      { type: "spreadsheet", name: "exceptions sheet", permission: "draft", required: false },
    ],
    steps: [
      { order: 1, instruction: "Match each invoice to its reference record." },
      { order: 2, instruction: "Flag amount, quantity, or party mismatches." },
      { order: 3, instruction: "Draft an exceptions report with the evidence for each mismatch." },
    ],
    outputSchema: { format: "table", requiredSections: ["invoice", "reference", "mismatch", "evidence", "suggested action"] },
    definitionOfDone: ["Every invoice is matched or flagged unmatched", "Each exception cites both records", "No payment is initiated"],
    approvalPolicy: { defaultMode: "read_only", approvalRequiredFor: ["any payment or adjustment"], blockedActions: ["approving payments", "editing invoices"] },
    riskChecks: ["financial commitment", "duplicate invoice", "segregation of duties"],
    evalTests: [{ name: "mismatch evidence", inputExample: "Invoice $1,100 vs PO $1,000", expectedOutput: "Exception cites both amounts." }],
    missingInfoQuestions: ["Which systems hold invoices and references?", "Who owns exception decisions?"],
  }),
  template({
    id: "wf-renewal-risk-brief",
    name: "Renewal risk brief",
    category: "summary",
    description: "Summarize upcoming renewals with health signals, open issues, and dollar exposure, flagging at-risk accounts.",
    delegationFit: "high",
    requiredInputs: [
      { name: "renewal list", description: "Accounts with renewal date, ARR, owner, and health score.", required: true },
      { name: "risk signals", description: "What counts as at-risk here (usage drop, open tickets, sentiment).", required: true },
    ],
    requiredTools: [{ type: "mcp", name: "customer platform", permission: "read", required: true }],
    steps: [
      { order: 1, instruction: "Pull renewals inside the window." },
      { order: 2, instruction: "Apply the risk signals to each account." },
      { order: 3, instruction: "Draft a brief ordered by dollar exposure and risk." },
    ],
    outputSchema: { format: "brief", requiredSections: ["renewal count", "dollar exposure", "at-risk accounts", "recommended plays"] },
    definitionOfDone: ["Covers the full window", "At-risk accounts cite their signals", "Recommendations stay internal"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["customer outreach", "discounting"], blockedActions: ["offering terms", "contacting customers"] },
    riskChecks: ["revenue exposure", "stale health data"],
    evalTests: [{ name: "risk ordering", inputExample: "Two renewals, one with usage drop", expectedOutput: "Flagged account leads with its signal cited." }],
    missingInfoQuestions: ["What renewal window matters?", "Which signals define at-risk?"],
  }),
  template({
    id: "wf-sop-compliance-check",
    name: "SOP compliance check",
    category: "classification",
    description: "Check completed work records against a standard operating procedure and flag deviations with evidence.",
    delegationFit: "medium",
    requiredInputs: [
      { name: "SOP document", description: "The procedure that defines compliant work.", required: true },
      { name: "work records", description: "The completed items to check.", required: true },
    ],
    requiredTools: [
      { type: "document_store", name: "SOP library", permission: "read", required: true },
      { type: "mcp", name: "work system", permission: "read", required: true },
    ],
    steps: [
      { order: 1, instruction: "Extract the checkable rules from the SOP." },
      { order: 2, instruction: "Evaluate each work record against each rule." },
      { order: 3, instruction: "Draft a deviations report citing the rule and the evidence." },
    ],
    outputSchema: { format: "table", requiredSections: ["record", "rule", "status", "evidence"] },
    definitionOfDone: ["Every record is evaluated", "Deviations cite the SOP clause", "No disciplinary inference is drawn"],
    approvalPolicy: { defaultMode: "read_only", approvalRequiredFor: ["any corrective action"], blockedActions: ["personnel conclusions", "editing work records"] },
    riskChecks: ["ambiguous SOP language", "personnel sensitivity"],
    evalTests: [{ name: "clause citation", inputExample: "Record missing a required approval step", expectedOutput: "Deviation cites the approval clause." }],
    missingInfoQuestions: ["Which SOP applies?", "Who reviews deviations?"],
  }),
  template({
    id: "wf-meeting-followup-draft",
    name: "Meeting follow-up draft",
    category: "drafting",
    description: "Turn meeting notes or a transcript into a follow-up draft with decisions, owners, and due dates.",
    delegationFit: "high",
    requiredInputs: [
      { name: "meeting record", description: "Notes or transcript of the meeting.", required: true },
      { name: "recipients", description: "Who the follow-up goes to.", required: true },
    ],
    requiredTools: [{ type: "email", name: "follow-up draft", permission: "draft", required: true }],
    steps: [
      { order: 1, instruction: "Extract decisions, action items, owners, and dates." },
      { order: 2, instruction: "Draft the follow-up grouped by owner." },
      { order: 3, instruction: "Flag items that left the meeting without an owner or date." },
    ],
    outputSchema: { format: "email_draft", requiredSections: ["decisions", "action items by owner", "open items", "next meeting"] },
    definitionOfDone: ["Every action item has an owner or is flagged", "Decisions quote the meeting", "Draft is not sent"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["sending"], blockedActions: ["external distribution"] },
    riskChecks: ["misattributed commitment", "external recipient"],
    evalTests: [{ name: "ownerless flag", inputExample: "Notes with one unowned task", expectedOutput: "Draft lists it under open items." }],
    missingInfoQuestions: ["Who receives the follow-up?", "Internal only, or customer-facing?"],
  }),
  template({
    id: "wf-kpi-variance-explanation",
    name: "KPI variance explanation",
    category: "reporting",
    description: "Explain why a KPI moved against target by tracing the variance to its component drivers, with evidence.",
    delegationFit: "medium",
    requiredInputs: [
      { name: "KPI definition", description: "The metric, its target, and how it is computed.", required: true },
      { name: "component data", description: "The underlying records that roll up into the KPI.", required: true },
    ],
    requiredTools: [
      { type: "mcp", name: "analytics source", permission: "read", required: true },
      { type: "spreadsheet", name: "variance workpaper", permission: "draft", required: false },
    ],
    steps: [
      { order: 1, instruction: "Compute the variance against target for the period." },
      { order: 2, instruction: "Decompose the variance into its component drivers." },
      { order: 3, instruction: "Draft an explanation ranking drivers by contribution, citing the data." },
    ],
    outputSchema: { format: "dashboard_note", requiredSections: ["variance", "top drivers", "evidence", "open questions"] },
    definitionOfDone: ["Drivers sum to the variance or the gap is stated", "Each driver cites data", "No forecast is changed"],
    approvalPolicy: { defaultMode: "read_only", approvalRequiredFor: ["publishing to leadership"], blockedActions: ["changing targets or forecasts"] },
    riskChecks: ["metric definition drift", "incomplete component data"],
    evalTests: [{ name: "driver ranking", inputExample: "KPI down 10% with one driver at -8%", expectedOutput: "That driver is ranked first at -8%." }],
    missingInfoQuestions: ["How exactly is this KPI computed?", "Who consumes the explanation?"],
  }),
  template({
    id: "wf-document-comparison",
    name: "Document comparison",
    category: "research",
    description: "Compare two or more document versions and report substantive differences, additions, and removals.",
    delegationFit: "high",
    requiredInputs: [{ name: "documents", description: "The versions or counterpart documents to compare.", required: true, example: "contract v2 vs v3" }],
    requiredTools: [{ type: "document_store", name: "document source", permission: "read", required: true }],
    steps: [
      { order: 1, instruction: "Align the documents section by section." },
      { order: 2, instruction: "Identify substantive changes, ignoring formatting." },
      { order: 3, instruction: "Draft a comparison report with side-by-side excerpts." },
    ],
    outputSchema: { format: "table", requiredSections: ["section", "change type", "before", "after", "significance"] },
    definitionOfDone: ["Every substantive change appears", "Excerpts quote both versions", "Legal significance is flagged, not judged"],
    approvalPolicy: { defaultMode: "read_only", approvalRequiredFor: ["any legal conclusion"], blockedActions: ["accepting or rejecting changes", "legal advice"] },
    riskChecks: ["legal interpretation", "missed redline"],
    evalTests: [{ name: "substantive only", inputExample: "Versions differing in one clause and one font", expectedOutput: "Report shows the clause, not the font." }],
    missingInfoQuestions: ["Which versions are canonical?", "Who reviews legal-flagged changes?"],
  }),
  template({
    id: "wf-crm-field-cleanup",
    name: "CRM field cleanup recommendation",
    category: "data_entry",
    description: "Find missing or inconsistent CRM field values and draft per-record corrections for human approval.",
    delegationFit: "medium",
    requiredInputs: [
      { name: "record scope", description: "Which CRM objects and fields to audit.", required: true },
      { name: "field standards", description: "Required fields and accepted value formats.", required: true },
    ],
    requiredTools: [{ type: "mcp", name: "CRM", permission: "write_with_approval", required: true }],
    steps: [
      { order: 1, instruction: "Audit the scoped records against the field standards." },
      { order: 2, instruction: "Draft a correction per violation, citing the source of the proposed value." },
      { order: 3, instruction: "Queue corrections for human approval before any write." },
    ],
    outputSchema: { format: "table", requiredSections: ["record", "field", "current value", "proposed value", "source"] },
    definitionOfDone: ["Every proposed value cites its source", "No write happens before approval", "Unknowns are flagged, not guessed"],
    approvalPolicy: { defaultMode: "execute_after_approval", approvalRequiredFor: ["every field write"], blockedActions: ["bulk writes without per-batch approval", "deleting records"] },
    riskChecks: ["silent data corruption", "guessing values without a source"],
    evalTests: [{ name: "no unsourced guess", inputExample: "Missing industry field with no evidence available", expectedOutput: "Record is flagged unknown, no value proposed." }],
    missingInfoQuestions: ["Which fields are required?", "Who approves the corrections?"],
  }),
];
