import type { WorkflowTemplate } from "@/types";

function template(base: Omit<WorkflowTemplate, "scope">): WorkflowTemplate {
  return { ...base, scope: "global" };
}

export const GLOBAL_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  template({
    id: "wf-weekly-status-summary",
    name: "Weekly status summary",
    category: "summary",
    description: "Summarize current work, risks, blockers, and approvals into a recurring internal brief.",
    delegationFit: "high",
    requiredInputs: [
      { name: "source records", description: "Work items, accounts, claims, tickets, or project updates to summarize.", required: true },
      { name: "date range", description: "The reporting window.", required: true, example: "previous business week" },
      { name: "recipient", description: "The human reviewer or team receiving the brief.", required: true },
    ],
    requiredTools: [
      { type: "mcp", name: "source system", permission: "read", required: true },
      { type: "email", name: "internal draft", permission: "draft", required: false },
    ],
    steps: [
      { order: 1, instruction: "Read the source records for the reporting window." },
      { order: 2, instruction: "Group records by status, owner, amount, and risk." },
      { order: 3, instruction: "Draft a brief with exceptions, missing data, and approval needs." },
    ],
    outputSchema: { format: "brief", requiredSections: ["summary", "exceptions", "approvals needed", "next actions"] },
    definitionOfDone: ["Includes count and aging", "Flags missing data", "Names owner and next action", "Never sends externally without approval"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["sending or publishing the brief"], blockedActions: ["changing source records", "approving exceptions"] },
    riskChecks: ["missing source fields", "stale records", "external recipient"],
    evalTests: [{ name: "sample summary", inputExample: "10 open records with 2 missing owners", expectedOutput: "Brief flags missing owners and separates exceptions." }],
    missingInfoQuestions: ["Which source system should the agent read?", "Who receives the brief?", "What cadence should it use?"],
  }),
  template({
    id: "wf-claims-summary",
    name: "Claims summary brief",
    category: "summary",
    description: "Summarize open customer or revenue claims with financial exposure, aging, owner, and approval needs.",
    delegationFit: "high",
    requiredInputs: [
      { name: "claims source", description: "System containing claims records.", required: true, example: "Salesforce claims object" },
      { name: "claim fields", description: "Status, amount, owner, aging, SLA, blockers.", required: true },
    ],
    requiredTools: [{ type: "mcp", name: "Salesforce", permission: "read", required: true }],
    steps: [
      { order: 1, instruction: "Pull open claims for the requested period." },
      { order: 2, instruction: "Group by status, owner, amount, and aging bucket." },
      { order: 3, instruction: "Draft an exceptions-first claims brief for human review." },
    ],
    outputSchema: { format: "brief", requiredSections: ["claim count", "dollar exposure", "aging", "exceptions", "approvals needed"] },
    definitionOfDone: ["Counts all open claims", "Shows dollar exposure", "Flags claims older than threshold", "Identifies missing data"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["claim approval", "customer communication"], blockedActions: ["approving claims", "editing customer records"] },
    riskChecks: ["PII exposure", "financial approval", "missing claim owner"],
    evalTests: [{ name: "missing owner test", inputExample: "10 claims, 1 missing owner", expectedOutput: "Brief includes all 10 and flags the missing owner." }],
    missingInfoQuestions: ["Where do claims live?", "What fields are required?", "What aging threshold matters?"],
  }),
  template({
    id: "wf-support-ticket-triage",
    name: "Support ticket triage",
    category: "routing",
    description: "Classify incoming support tickets, flag risk, and draft routing recommendations.",
    delegationFit: "high",
    requiredInputs: [{ name: "ticket queue", description: "Ticket list with requester, issue, severity, and owner.", required: true }],
    requiredTools: [{ type: "mcp", name: "Zendesk", permission: "read", required: true }],
    steps: [{ order: 1, instruction: "Read new tickets." }, { order: 2, instruction: "Classify severity and category." }, { order: 3, instruction: "Draft routing recommendation." }],
    outputSchema: { format: "table", requiredSections: ["ticket", "category", "severity", "suggested owner", "reason"] },
    definitionOfDone: ["Every ticket has a category", "High-risk items are flagged", "Recommendations cite evidence"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["closing tickets", "customer-facing replies"], blockedActions: ["closing tickets without approval"] },
    riskChecks: ["customer escalation", "security issue", "missing owner"],
    evalTests: [{ name: "severity routing", inputExample: "Three tickets with one outage report", expectedOutput: "Outage ticket marked high severity." }],
    missingInfoQuestions: ["Which queue should be triaged?", "Who approves routing changes?"],
  }),
  template({
    id: "wf-approval-packet",
    name: "Approval packet preparation",
    category: "approval_prep",
    description: "Prepare an internal packet with facts, evidence, risks, and recommended approval questions.",
    delegationFit: "medium",
    requiredInputs: [{ name: "request details", description: "The request needing approval and supporting facts.", required: true }],
    requiredTools: [{ type: "document_store", name: "policy documents", permission: "read", required: false }],
    steps: [{ order: 1, instruction: "Collect request facts." }, { order: 2, instruction: "Compare against approval policy." }, { order: 3, instruction: "Draft approval packet." }],
    outputSchema: { format: "brief", requiredSections: ["request", "policy context", "risks", "approval questions"] },
    definitionOfDone: ["Cites source facts", "Separates recommendation from decision", "Names human approver"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["final approval"], blockedActions: ["approving on behalf of the human"] },
    riskChecks: ["financial authority", "policy exception"],
    evalTests: [{ name: "approval boundary", inputExample: "Refund request above threshold", expectedOutput: "Packet says human approval required." }],
    missingInfoQuestions: ["Who approves this?", "Which policy applies?"],
  }),
  template({
    id: "wf-internal-update-draft",
    name: "Internal update draft",
    category: "drafting",
    description: "Draft an internal status update from source notes and known operating facts.",
    delegationFit: "high",
    requiredInputs: [{ name: "source notes", description: "Meeting notes, task records, or transcript excerpts.", required: true }],
    requiredTools: [{ type: "email", name: "email or Slack", permission: "draft", required: false }],
    steps: [{ order: 1, instruction: "Extract facts and open decisions." }, { order: 2, instruction: "Draft concise internal update." }],
    outputSchema: { format: "email_draft", requiredSections: ["context", "updates", "asks", "owner"] },
    definitionOfDone: ["Draft is internal", "Asks are explicit", "No unsupported commitments"],
    approvalPolicy: { defaultMode: "draft_for_approval", approvalRequiredFor: ["sending"], blockedActions: ["external communication"] },
    riskChecks: ["unsupported promise", "external recipient"],
    evalTests: [{ name: "draft only", inputExample: "Meeting notes with two asks", expectedOutput: "Draft update includes both asks and stays unsent." }],
    missingInfoQuestions: ["Who receives the update?", "What tone/cadence should it use?"],
  }),
];
