import type { CompiledAgent, RuntimeAdapter, RuntimeArtifact, ValidationWarning } from "./types";
import { buildHermesManifest, buildHermesYamlFrontMatter, type HermesAgentManifest } from "../hermesManifest";
import { slugify } from "../agent";

export const hermesAdapter: RuntimeAdapter = {
  id: "hermes",
  label: "Hermes",
  description: "SOUL.md operator contract + executable Hermes package with skills",
  emit(input: CompiledAgent): RuntimeArtifact[] {
    const hermes = buildHermesManifest({ ...input.manifest, system_prompt: input.system_prompt });
    const artifacts: RuntimeArtifact[] = [
      { path: "SOUL.md", content: buildSoul(input, hermes.manifest), mime: "text/markdown" },
      { path: "config.yaml", content: buildConfigYaml(hermes.manifest), mime: "text/yaml" },
      { path: "distribution.yaml", content: buildDistributionYaml(hermes.manifest), mime: "text/yaml" },
      { path: "hermes-manifest.json", content: JSON.stringify(hermes.manifest, null, 2), mime: "application/json" },
      { path: "hermes-agent.md", content: hermes.markdown, mime: "text/markdown" },
    ];
    for (const skill of buildSkills(input)) {
      artifacts.push(
        { path: `skills/${skill.slug}/SKILL.md`, content: skill.skillMd, mime: "text/markdown" },
        { path: `skills/${skill.slug}/references/evidence.md`, content: skill.references, mime: "text/markdown" },
      );
    }
    return artifacts;
  },
  validate(input: CompiledAgent): ValidationWarning[] {
    const warnings: ValidationWarning[] = [];
    const schedule = input.construction_spec.recommended_schedule;
    if (input.construction_spec.operating_mode === "scheduled" && !schedule?.cron) {
      warnings.push({ code: "hermes_missing_cron", message: "Scheduled Hermes agent has no cron expression; the package ships with TODO_CRON." });
    }
    return warnings;
  },
};

// ── SOUL.md: sectioned operator contract per docs/soul-agent-operator-contract.md ──

function buildSoul(input: CompiledAgent, hermes: HermesAgentManifest): string {
  const spec = input.construction_spec;
  const owner = input.owner;
  const gov = input.governance;
  const escalate = [
    ...gov.approval.map((a) => `${a.action} — requires approval from ${a.approver}${a.rule_id ? ` (rule ${a.rule_id})` : ""}`),
    ...spec.escalation_rules,
  ];
  const evidence = input.task.evidence ? `\n> Evidence from discovery: "${input.task.evidence}"` : "";

  return `# SOUL.md — ${input.agent_name}

> Operator contract compiled by Pedigree v${input.version} for ${owner.name} (${owner.title}, ${owner.department}).
> Trace: ${input.provenance.trace_id} · compiled ${input.provenance.compiled_at}

## Core Identity
${spec.role}

## Primary Mission
${spec.purpose} ${spec.goal}${evidence}

## Active Priorities
${bullets(spec.workflow_steps)}

## Lower Priority / Cleanup Areas
- Anything outside the parent responsibility "${input.responsibility.title}".
- Do not expand scope beyond the anchored task "${input.task.label}" without a recompiled manifest.

## Tone & Communication
${spec.output_style}

## Autonomy Boundaries

### May do without asking
${bullets(gov.allowed)}

### Must escalate before
${bullets(escalate)}

### Never (blocked)
${bullets(gov.blocked.map((b) => `${b.action}${b.rule_id ? ` (rule ${b.rule_id})` : ""}`))}

## Escalation
Escalate to ${owner.name} <${owner.email}>. ${spec.authority_ceiling}

## Pushback & Standards
If a request would cross an autonomy boundary, push back and cite the boundary. Risk tier: ${input.risk_level}. When the request ignores governance constraints, name the specific rule and refuse.

## Accountability & Output Rules
- Audit events: ${spec.audit_events.join("; ") || "none"}
- Memory policy: ${spec.memory_policy}
- Every deliverable is a draft for ${owner.name}'s review unless explicitly listed under "May do without asking".
${gov.rule_provenance.length ? `\n### Governance provenance\n${gov.rule_provenance.map((p) => `- ${p.rule_id} (${p.source_doc}): "${p.evidence_quote}"`).join("\n")}` : ""}`;
}

function buildConfigYaml(hermes: HermesAgentManifest): string {
  return [
    `# Hermes runtime config — generated by Pedigree`,
    buildHermesYamlFrontMatter(hermes),
    `model:`,
    `  provider: ${hermes.model?.provider ?? "openai"}`,
    `  model: ${hermes.model?.model ?? "runtime_default"}`,
  ].join("\n");
}

function buildDistributionYaml(hermes: HermesAgentManifest): string {
  const lines: string[] = ["# Delivery & distribution — generated by Pedigree", "delivery:"];
  const emitTargets = (key: string, targets: { platform: string; recipient: string; channel?: string; format?: string }[]) => {
    lines.push(`  ${key}:`);
    if (!targets.length) {
      lines.push("    []");
      return;
    }
    for (const t of targets) {
      lines.push(`    - platform: ${t.platform}`);
      lines.push(`      recipient: ${JSON.stringify(t.recipient)}`);
      if (t.channel) lines.push(`      channel: ${JSON.stringify(t.channel)}`);
      lines.push(`      format: ${t.format ?? "brief"}`);
    }
  };
  emitTargets("on_complete", hermes.delivery.on_complete);
  emitTargets("on_error", hermes.delivery.on_error);
  emitTargets("on_approval", hermes.delivery.on_approval);
  lines.push(`  format: ${hermes.delivery.format}`);
  return lines.join("\n");
}

// ── Skills: one lean SKILL.md per workflow pattern (~500 tokens) ───────

interface HermesSkill {
  slug: string;
  skillMd: string;
  references: string;
}

function buildSkills(input: CompiledAgent): HermesSkill[] {
  const spec = input.construction_spec;
  const patterns = new Set<string>();
  const candidate = input.task.completion?.candidate_pattern;
  if (candidate) patterns.add(slugify(candidate));
  for (const skill of spec.skills) {
    const slug = slugify(skill);
    if (slug) patterns.add(slug);
  }
  if (!patterns.size) patterns.add(slugify(input.task.label).split("-").slice(0, 4).join("-") || "primary-task");

  return Array.from(patterns).slice(0, 4).map((slug) => ({
    slug,
    skillMd: buildSkillMd(slug, input),
    references: buildReferences(input),
  }));
}

function buildSkillMd(slug: string, input: CompiledAgent): string {
  const spec = input.construction_spec;
  const completion = input.task.completion;
  // Kept lean (~500 tokens): workflow, inputs, outputs, done, boundaries. Deep
  // evidence lives in references/.
  return `---
name: ${slug}
description: ${spec.purpose}
---

# ${titleCase(slug)}

Task: ${input.task.label} (responsibility: ${input.responsibility.title}).
${completion?.trigger ? `Trigger: ${completion.trigger}.` : "Trigger: on request from the owner."}

## Steps
${bullets(spec.workflow_steps.slice(0, 6))}

## Inputs
${bullets((completion?.inputs?.length ? completion.inputs : spec.input_requirements).slice(0, 5))}

## Outputs
${bullets((completion?.outputs?.length ? completion.outputs : spec.output_artifacts).slice(0, 5))}

## Definition of done
${completion?.definition_of_done ?? "Output prepared as a draft and delivered for owner review."}

## Boundaries
- Approval required: ${input.governance.approval.map((a) => a.action).join("; ") || "none"}
- Blocked: ${input.governance.blocked.slice(0, 5).map((b) => b.action).join("; ")}

See \`references/evidence.md\` for transcript evidence and governance provenance.`;
}

function buildReferences(input: CompiledAgent): string {
  const completion = input.task.completion;
  const lines = [
    `# Evidence — ${input.task.label}`,
    "",
    input.task.evidence ? `Transcript evidence: "${input.task.evidence}"` : "No direct transcript evidence captured.",
  ];
  if (completion?.open_questions?.length) {
    lines.push("", "## Open questions", ...completion.open_questions.map((q) => `- ${q}`));
  }
  if (input.governance.rule_provenance.length) {
    lines.push("", "## Governance provenance", ...input.governance.rule_provenance.map((p) => `- ${p.rule_id} (${p.source_doc}): "${p.evidence_quote}"`));
  }
  return lines.join("\n");
}

function bullets(items: string[]): string {
  return items.length ? items.map((i) => `- ${i}`).join("\n") : "- (none)";
}

function titleCase(slug: string): string {
  return slug.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}
